# node stage

FROM node:20-alpine as build

WORKDIR /usr/app/client

COPY package.json ./
COPY yarn.lock .

RUN yarn install --immutable --immutable-cache --check-cache

COPY . .

RUN yarn build:dev 

CMD ["yarn", "preview"]

# nginx stage

FROM nginx:1.25.5-alpine

WORKDIR /usr/share/nginx/html

COPY --from=build /usr/app/client/dist .

RUN rm -rf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/app/client/nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 4173
CMD ["nginx", "-g", "daemon off;"]