[build]
  command = "yarn run build"
  publish = "dist"

[context.production]
  command = "yarn run build"

[context.branch-deploy]
  command = "yarn run build:dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200